services:
  ros-melodic:
    build:
      context: .
      dockerfile: ros.Dockerfile
    container_name: ros-melodic
    restart: unless-stopped
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    stdin_open: true
    tty: true