services:
  ros-melodic:
    build:
      context: .
      dockerfile: ros.Dockerfile
      args:
        USERNAME: jetauto
        USER_UID: 1000
        USER_GID: 1000
    container_name: ros-melodic
    restart: unless-stopped
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    # devices:
    #   - /dev/dri:/dev/dri
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]