services:
  ros:
    build:
      context: .
      dockerfile: ros.Dockerfile
    image: ros-melodic-dev
    container_name: ros-melodic-container
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/jetauto:/mnt/host
    working_dir: /mnt/host
    devices:
      - /dev/dri
      - /dev/input:/dev/input
    stdin_open: true
    tty: true
    privileged: true