services:
  ros-ubuntu:
    build:
      context: .
      dockerfile: ros-ubuntu.Dockerfile
      args:
        - CUSTOM_CATKIN_WS_DIR=/mnt/host/Desktop/Seneca_Class_Notes/Semester 2/AIG240 - Robotics/ros_ws/catkin_ws
    image: ros-ubuntu:lab
    container_name: ros_ubuntu_container
    # Common settings for both containers
    network_mode: host                # Use 'host' for easier ROS networking & GUI (change if conflicts)
    ports:
      # - "22:22"              # SSH from host → container directly (port 22)
      - "2222:22"   # Host port 2222 → container's port 22
    # command: /usr/sbin/sshd -D
    environment:
      - DISPLAY=${DISPLAY}            # Use your system's DISPLAY variable for GUI
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/jetauto:/mnt/host
      # - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /etc/localtime:/etc/localtime:ro
    working_dir: /mnt/host
    devices:
      - /dev/dri
      - /dev/input:/dev/input
    stdin_open: true
    tty: true
    privileged: true

  ros-official:
    build:
      context: .
      dockerfile: ros-official.Dockerfile
      args:
        - CUSTOM_CATKIN_WS_DIR=/mnt/host/Desktop/Seneca_Class_Notes/Semester 2/AIG240 - Robotics/ros_ws/catkin_ws
    image: ros-official:lab
    container_name: ros_official_container
    # Common settings for both containers
    network_mode: host                # Use 'host' for easier ROS networking & GUI (change if conflicts)
    ports:
      # - "22:22"              # SSH from host → container directly (port 22)
      - "2222:22"   # Host port 2222 → container's port 22
    # command: /usr/sbin/sshd -D
    environment:
      - DISPLAY=${DISPLAY}            # Use your system's DISPLAY variable for GUI
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/jetauto:/mnt/host
      # - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /etc/localtime:/etc/localtime:ro
    working_dir: /mnt/host
    devices:
      - /dev/dri
      - /dev/input:/dev/input
    stdin_open: true
    tty: true
    privileged: true