services:
  ros:
    build:
      context: .
      dockerfile: ros.Dockerfile
    image: ros-melodic-dev
    container_name: ros-melodic-container-gpu
    user: "1000:1000"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri  # iGPU support
    devices:
      - /dev/dri
    stdin_open: true
    tty: true